create skeleton java springboot app for accounts-filing-api
companieshouse/accounts-filing-api pull request #2
Opened 2023-06-27 11:59 UTC by myadavch

Adding authentication, logging and other dependencies in the api skeleton.

2023-06-27 12:52 UTC, wdhda-ch commented on Tiltfile.dev
> +  ref = '169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/account-filing-api',
`/account-filing-api` is missing an "s"?

Should it be `/accounts-filing-api` ?

2023-06-27 12:52 UTC, wdhda-ch commented on Tiltfile.dev
> +           argv=['sh', '-c', 'if [ "$(tilt status --resource account-filing-api)" = "enabled" ]; then tilt disable my_resource; else tilt enable account-filing-api; fi'],
Should it be /accounts-filing-api ?

2023-06-27 12:53 UTC, wdhda-ch commented on routes.yaml
> +app_name: account-filing-api
Should it be accounts-filing-api ?

2023-06-27 12:54 UTC, wdhda-ch commented on src/main/java/uk/gov/companieshouse/account/filing/AccountFilingApiApplication.java
> +		SpringApplication.run(AccountFilingApiApplication.class, args);
Should it be `AccountsFilingApiApplication` ?

2023-06-28 11:11 UTC, myadavch commented on Tiltfile.dev
> +  ref = '169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/account-filing-api',
Done

2023-06-28 11:11 UTC, myadavch commented on Tiltfile.dev
> +           argv=['sh', '-c', 'if [ "$(tilt status --resource account-filing-api)" = "enabled" ]; then tilt disable my_resource; else tilt enable account-filing-api; fi'],
Done

2023-06-28 11:11 UTC, myadavch commented on routes.yaml
> +app_name: account-filing-api
Done

2023-06-28 11:11 UTC, myadavch commented on src/main/java/uk/gov/companieshouse/account/filing/AccountFilingApiApplication.java
> +		SpringApplication.run(AccountFilingApiApplication.class, args);
Done

2023-06-28 11:16 UTC, amartin7663 approved these changes

2023-06-28 11:18 UTC, amartin7663 requested changes

2023-06-28 11:18 UTC, amartin7663 commented on README.md
> +# account-filing-api
Still have account not accounts in the read me

2023-06-28 11:18 UTC, amartin7663 commented on Tiltfile.dev
> +  name = 'dev:account-filing-api',
accounts here

2023-06-28 13:53 UTC, amartin7663 commented on README.md
> +A service to manage user's account for all their filings.This application is written using the [Spring Boot](http://projects.spring.io/spring-boot/) Java framework.
I think I prefer the original text so something like this
```suggestion
A backend service allowing users to submit accounts in zip format. This application is written using the [Spring Boot](http://projects.spring.io/spring-boot/) Java framework.
```

2023-06-28 14:02 UTC, amartin7663 approved these changes

2023-06-28 14:14 UTC, merged